### PR TITLE
have travis test python 3.4 as well

### PR DESCRIPTION
**Pull request by ryan-williams**

### CODE REVIEW

**Comment by ryan-williams** [comment]
@danvk does this look like all I need?

**Comment by ryan-williams** [comment]
Old-style print statements in tests, need to fix... not sure if I should push this first or not.

**Comment by ryan-williams** [comment]
Added this commit to #70 in the meantime, hopefully we can just merge everything in in one shot over there

**Comment by danvk** [comment]
Yep, this is all you need!

**Comment by ryan-williams** [comment]
thx, going to fold this in to #70

**Pull request closed without merging**
