### PR TITLE
Allow `github <path>`

### LINKED ISSUE #59: `github path/to/file` should open that file in the browser
Would be helpful for sending out links to files.

### PR DESCRIPTION
**Pull request by danvk**
Fixes #59 

I punted on referencing the current tree—if you have ideas on how to make sure the current tree exists on GitHub, I'm all ears.

### CODE REVIEW

**Comment by ryan-williams** [comment]
lgtm.

inspired by [this SO](http://stackoverflow.com/questions/5549479/git-check-if-commit-xyz-in-remote-repo), `git branch -r --contains 1e3478d` prints out remote branches that contain `1e3478d` (your commit SHA here).

Somewhat hackily parse the output:
```
git branch -r --contains 1e3478d | grep -q 'origin/'
```

To fully oneline it:
```
git branch -r --contains "$(git sha HEAD)" | grep -q 'origin/'
```
 Anyway we can try adding some smarts around that later. This seems good.

**Comment by danvk** [comment]
Would that require running `git fetch` first, or does it actually go out and check the remote?

**Comment by ryan-williams** [comment]
it would not check the remote by itself, but it could still be a good
approximation if you are reasonably current.

we could have it take a `-p` flag that would push the current tree up under
the current branch name.

or you could do your own `push` before using this command to get a link.

I could even imagine something like a `-o` flag to `push` (or some alias
thereof that we control, like `spf`) that would open the tree in your
browser.

anyway, all solutions looking for a problem at the moment, let's use this
and see how we like it.

another slightly orthogonal improvement, as long as we're opening `path` on
`origin/master`, could be to have a flag that would open `path` on the
latest commit on `origin/master` (basically just pressing "y" for you on
page load).

I'm not desperate for any of this though.

**Comment by danvk** [comment]
Yeah, I figure you can just press `y` if you want a permalink.

**Pull request merged**
